#!/bin/sh -e

eventid=$1
fn=$2

mkdir -p /tmp/motion/processed

dn=`dirname $fn`
bn=`basename $fn .avi`
nn="$dn/$bn.mp4"

avconv -v error -i $fn $nn
mv $fn /tmp/motion/processed

echo "Saved vid $nn" | logger -t motion
