#!/usr/local/bin/perl

sub quote
{
	my($t)=@_;

	$t=~s/\'/\\\'/g;
	return("'$t'");
}

$data="";
$title="";

while(<>) {
	chomp;
	s/\s*twowayAlerts.com\s*//gi;
	if(/\[!A0\]\[D32801\]!\*\s*(.*?)\s*(\;.*\*!)/) {
		$title=$1;
		/(\[!A0\]\[D32801\]!.*\*!)/;
		$data=$1;
		while($_=<> && ($_!~/\*\!/)) {
			chomp;
			$data.=$_;
		}
		print "insert into music(title, data) values(" . quote($title)
			. ", " . quote($data) . ");\n";
	}
}
