#!/usr/local/bin/perl
# Copyright (c) 1999  Dustin Sallings
# $Id: parseamanda,v 1.3 1999/08/30 19:19:53 dustin Exp $

sub getmonth
{
	my($month)=@_;
	my(%months);

	%months=( 'January' => 1, 'February' => 2, 'March' => 3, 'April' => 4,
		'May' => 5, 'June' => 6, 'July' => 7, 'August' => 8, 'September' => 9,
		'October' => 10, 'November' => 11, 'December' => 12
	);
	return(sprintf("%02d", $months{$month}));
}

sub monthly_averages
{
	my($year)=@_;
	my($month, $day, $total, $count, $min, $max, $avg, %avg);

	for $month (sort(keys(%{$year}))) {
		$total=0; $count=0; $max=-1; $min=999999999999;
		for $day (keys(%{$year->{$month}})) {
			if($year->{$month}{$day}{'Original'} > $max) {
				$max=$year->{$month}{$day}{'Original'};
			}
			if($year->{$month}{$day}{'Original'} < $min) {
				$min=$year->{$month}{$day}{'Original'};
			}
			$total+=$year->{$month}{$day}{'Original'};
			$count++;
		}
		$avg=$total/$count;
		$avg{$month}="$min $avg $max";
	}

	return(%avg);
}

while(<>) {
	next unless(/^Subject: WestSPY AMANDA MAIL REPORT FOR (\w+) (\d+), (\d+)/);

	if($3 < 1990) {
		print STDERR "Error on $_\n";
		next;
	}

	my($year, $mon, $day)=($3, getmonth($1), sprintf("%02d", $2));

	while($_=<>) {
		if(/^Output Size .meg.\s+([0-9\.]+)/o) {
			$store{$year}{$mon}{$day}{'Output'}=$1;
		} elsif(/^Original Size .meg.\s+([0-9\.]+)/o) {
			$store{$year}{$mon}{$day}{'Original'}=$1;
		}

		last if(/^From /);
	}
	last if(eof());
}

for $year (sort(keys(%store))) {
	print "$year\n";
	%avg=monthly_averages($store{$year});
	open(OUT, ">$year.avg");
	for(sort(keys(%avg))) {
		print OUT "$_ $avg{$_}\n";
	}
	close(OUT);
	for $mon (sort(keys(%{$store{$year}}))) {
		print "\t$mon\n";
		open(OUT, ">$year-$mon.dat");
		for $day (sort(keys(%{$store{$year}{$mon}}))) {
			print OUT "$day $store{$year}{$mon}{$day}{'Output'} " .
				"$store{$year}{$mon}{$day}{'Original'}\n";
			print "\t\t$day: $store{$year}{$mon}{$day}{'Output'}:".
				"$store{$year}{$mon}{$day}{'Original'}\n";
		}
		close(OUT);
	}
}
