#!/usr/local/bin/perl
# Copyright (c) 1997  Dustin Sallings
#
# $Id: checkwebserver,v 1.1 1997/11/20 08:05:54 dustin Exp $
# $Source: /Users/dustin/stuff/cvstest/perl/net/checkwebserver,v $

use Socket;

sub GetStatus
{
    my($url)=@_;
    my($host, $request, @status);

    if($url eq "")
    {
	return("", 0, "Invalid URL format");
    }

    if(!($url=~/http:\/\/([^\/]+)(.*)/))
    {
	return("", 0, "Invalid URL format");
    }

    ($host, $request)=($1, $2);

    $request="/" if($request eq "");

    # print "Getting $request from $host\n";

    $proto=getprotobyname('tcp');
    socket(S, PF_INET, SOCK_STREAM, $proto);
    $sin=sockaddr_in(80, inet_aton($host));
    connect(S, $sin);

    print S "GET $request HTTP/1.0\n\n";

    chop($in=<S>);
    @status=split(/\s+/, $in, 3);
    return(@status);
}

for(@ARGV)
{
    @status=GetStatus($_);
    print "$_:  $status[1]\n";
}
