#!/usr/local/bin/perl
# This was written by Dustin Sallings for David Rarick for use with
# MobileComm's WWW Paging Client thing.
# Made to work under IRIX 6.2, should work anywhere, probably doesn't.
# $Id: webpage,v 1.2 1997/11/24 06:28:55 dustin Exp $

use Socket;

# Username -> pin mapping
%Users=(
    'drarick' => 8203941,
);

# In case of an alarm (connection timeout), just reset the alarm handler
# and return.

sub alarmhandler
{
    alarm(0);
    $SIG{'ALRM'}=alarmhandler;
    return(0);
}

# Encode a character into a %XX value.

sub myurlencode
{
    my($char)=@_;
    my($return);

    $return=unpack("c", $char);
    $return=sprintf("%%%X", $return);
    return($return);
}

sub SendPage
{
    my($pin, $message)=@_;
    my($host, $formdata);

    $host="www.mobilecomm.com";

    $proto=getprotobyname('tcp');
    socket(S, PF_INET, SOCK_STREAM, $proto);
    $sin=sockaddr_in(80, inet_aton($host));

    # Thirty seconds should be plenty long enough to connect.
    $SIG{'ALRM'}=alarmhandler;
    alarm(30);
    connect(S, $sin) || return(0);
    alarm(0);

    $message=~s/([^A-z0-9])/&myurlencode($1)/ge;
    $formdata="PIN=$pin&MSSG=$message";

    print S "POST /scripts/mobilecomm/wwwpage.exe HTTP/1.0\n";
    print S "Content-length: " . length($formdata) . "\n";
    print S "Content-type: application/x-www-form-urlencoded\n\n";
    print S $formdata;

    # This eats the web page they send us.
    while(<S>) {}
}

#################################################
#
# This is the beginning.
#
#################################################

# Grab the arguments.  First arg is a pin, everything after that is
# combined with a space to make the message.

$pin=shift;
if($pin=~/[A-z]/)
{
    $pin=$Users{$pin};
}

$message=join(' ', @ARGV);

# Call the page sender.

SendPage($pin, $message);
