#!/bin/sh
# arch-tag: 22288C0F-4A64-11D8-81A6-003065ABF26A

# PWD=/Users/dustin/bak/db
# PREVPATH=/tmp/prev/00249
# NEWPATH=/tmp/new/00249
# PREVDIR=/tmp/prev
# SHLVL=2
# DIGEST=86b75c42abd2156cba20885ad5e13a50
# BLOCK=249
# NEWDIR=/tmp/new

HOME=/Users/dustin
export HOME

PWH=$HOME/bin/powerpc-apple-darwin/passwordhander
GPG=$HOME/local.bin/gpg

touch /tmp/gpg.out

mkdir -p `dirname $PREVPATH`
$PWH $HOME/.sigpw $GPG -se --passphrase-fd 4 \
	--batch -r primary -r work > $PREVPATH.tmp 2>> /tmp/gpg.out \
	&& mv $PREVPATH.tmp $PREVPATH

exit 0
