#!/bin/sh
# arch-tag: 00C2C6A5-4A64-11D8-AD0A-003065ABF26A

DEST=$1

if [ "x$DEST" = "x" ]
then
	DEST=$HOME/bak/db
fi

cat <<EOF
*
* Dumping databasen at `date` to $DEST
*
EOF

(

PLACE=$DEST
GPG=/usr/local/bin/gpg

mkdir -p $PLACE
cd $PLACE

THISHOST='rubik'

for host in rubik
do
	echo "Doing host $host"
	PSQL="/usr/local/pgsql/bin/psql"
	PDUMP="/usr/local/pgsql/bin/pg_dump -F c      "
	if [ "$host" != "$THISHOST" ]
	then
		PSQL="$PSQL -h $host"
		PDUMP="/usr/local/pgsql/bin/pg_dump -h $host"
	fi
	W="where datname not in ('template0', 'template1')"
	# W="where datname in('spyshop', 'money')"

	for i in `$PSQL -t -c "select datname from pg_database $W" template1`
	do
		echo "Analyzing $i ..."
		$PSQL -c "analyze;" $i

		echo "Dumping..."
		$PDUMP $i | $HOME/bin/db_dumps_stream $PLACE $i

		echo ""

	done

    wait
done

)
