#!/bin/sh

PATH=$PATH:$HOME/bin/
export PATH

hgdir=$PWD

everything=`wget -q -O - http://rubik.west.spy.net/~dustin/hglist.txt`

for s in $everything
do
	if [ ! -d $hgdir/$s ]
	then
		cd $hgdir
		echo "Bootstrapping $s"
		if [ ! -d `dirname $s` ]
		then
			d=`dirname $s`
			echo "Creating $d"
			mkdir -p $d
		fi
		hg clone -U http://rubik.west.spy.net/hg/$s $s
	fi
done

for f in `find $hgdir -name .hg`
do
	d=`dirname $f`
	echo "Doing $d"
	cd $d
	hg incoming
	hg pull
done
