#!/bin/sh
# arch-tag: 89069-014-11-8-0030187026

place=$1
dbname=$2

GPG=/usr/local/bin/gpg

today=`date +%Y%m%d`
unixtoday=`date +%s`
unixyesterday=`expr $unixtoday - 86400`
yesterday=`date -r $unixyesterday +%Y%m%d`

runCommand() {
	touch /tmp/stream.debug
	echo "$@" >> /tmp/stream.debug
	"$@"
}

blocksize=""
if [ -f $HOME/.dump-params/$dbname ]
then
	blocksize=`cat $HOME/.dump-params/$dbname`
else
	if [ -f $HOME/.dump-params/=default ]
	then
		blocksize=`cat $HOME/.dump-params/=default`
	fi
fi

touch $place/../db.digests/$dbname
mkdir -p $today/$dbname
$HOME/local.bin/blockDigest - "$place/../db.digests/$dbname" \
	$HOME/local.bin/encryptBlock $yesterday/$dbname $today/$dbname $blocksize

du -sk $today/$dbname
