-- Each new term in the Fibonacci sequence is generated by adding the
-- previous two terms. By starting with 1 and 2, the first 10 terms will
-- be:

--   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

-- Find the sum of all the even-valued terms in the sequence which do not
-- exceed four million.

fib :: Integer -> Integer

fib 0 = 0
fib 1 = 1
fib n = fib (n-1) + fib (n-2)

fibs = [ fib x | x <- [1..]]

euler2 n = sum [ x | x <- takeWhile (<= n) fibs, even x ]