#!/bin/sh

RSYNC=rsync

$RSYNC -varltpogHS --password-file=.rsyncpw \
	--delete --stats --progress dustin@disk::dustindbbak/ db/

$RSYNC -varltpogHS --password-file=.rsyncpw \
	--delete --stats dustin@disk::dustinsfcvs/ sfcvs/

$RSYNC -varltpogHS --password-file=.rsyncpw \
	--exclude='rcache.*' \
	--exclude='*.old' \
	--delete --stats dustin@disk::dustinbak/tars/ tars/

