#!/bin/sh
#
# arch-tag: AFFC1B1C-4162-11D8-9523-000393CFE6B8

RSYNC=rsync

$RSYNC -varltpogS --password-file=.rsyncpw \
	--delete --stats --progress dustin@disk::dustindbbak/db/ db/

$RSYNC -varltpogS --password-file=.rsyncpw \
	--delete --stats dustin@disk::dustinsfcvs/ sfcvs/

$RSYNC -varltpogS --password-file=.rsyncpw \
	--exclude='rcache.*' \
	--exclude='*.old' \
	--delete --stats dustin@disk::dustinbak/tars/ tars/

