#!/usr/local/bin/perl
#
# Copyright (c) 1997  Dustin Sallings
#
# $Id: billthepoor,v 1.2 1997/10/23 08:06:47 dustin Exp $

use Postgres;

require 'billib.pl';

# Let's use money precision, since that's what we're asking for.
$#="%.2f";

if(!($dbh=db_connect("spam")))
{
    die("Error:  $Postgres::error\n");
}

sub makebill
{
    my($dbh, $inv)=@_;
    my(%h);

    %h=getInvInfo($dbh, $inv);

    foreach $key (keys(%h))
    {
	$h{$key}=~s/([#\$\&])/\\$1/g;
    }

    open(OUT, ">out/$h{'spam_id'}.tex");
    print OUT <<EOF;
\\documentclass[11pt]{article}

\\usepackage{fullpage}
\\usepackage{bills}

\\begin{document}

\\pagestyle{empty}

\\billfrom{%
Dustin Sallings\\\\
655 South Fair Oaks \\#K202\\\\
Sunnyvale, CA  94086\\\\
info\@west.spy.net
}

\\billto{%
$h{'name'}\\\\
$h{'addr1'}\\\\
EOF

print OUT "$h{'addr2'}\\\\\n" if($h{'addr2'}=~/[A-z0-9]+/);

print OUT <<EOF;
$h{'city'}, $h{'state'}  $h{'zip'}\\\\
$h{'email'}
}

\\billacctid{$h{'spam_id'}}
\\billdate{$h{'billdate'}}
\\billstart{$h{'billstart'}}
\\billend{$h{'billend'}}
\\billnumber{$h{'invoice'}}

\\billcharges{$h{'debit'}}
\\billforward{$h{'forward'}}
\\billcredits{$h{'credit'}}
\\billtotal{$h{'total'}}

\\makebill{spy.net}{%
EOF

    foreach $s (@{$h{'trans'}})
    {
        @r=@{$s};
        if($r[2]>0)
        {
            print OUT "$r[0] & $r[1] & \\$r[2] & \\\$0.00\\\\\\hline\n";
        }
        else
        {
            print OUT "$r[0] & $r[1] & \\\$0.00 & \\$r[2] \\\\\\hline\n";
        }
    }

    print OUT <<EOF;
}

\\end{document}
EOF

    close(OUT);
}

#################### START #########################

$query="select invoice from invoices";
$s=doQuery($dbh, $query);

while(($inv)=$s->fetchrow())
{
    print "Doing invoice $inv\n";
    makebill($dbh, $inv);
}
