#!/usr/local/bin/perl
# Copyright (c) 1997  Dustin Sallings
# $Id: createinvs,v 1.2 1998/01/12 09:12:40 dustin Exp $

use Postgres;

sub doquery
{
    my($query)=@_;
    my($s);

    if(!($s=$dbh->execute($query)))
    {
        die("Error:  $Postgres::error\n$query");
    }
    return($s);
}

sub getdates
{
    my(@lastof, @ltime, $m, $y, $start, $end);
    @lastof=(0,31,28,31,30,31,30,31,31,30,31,30,31);
    @ltime=localtime();
    $m=$ltime[4]+1;
    $y=$ltime[5]+1900;

    $start="$m/01/$y";
    $end="$m/$lastof[$m]/$y";

    return($start, $end);
}

if($#ARGV<1)
{
    ($start, $end)=&getdates;
}
else
{
    ($start, $end)=@ARGV;
}

print "Creating invoices for $start - $end\n";

$dbh=db_connect("spam");

$query ="select distinct spam_id from trans where ts>='$start'\n";
$query.="    and ts<='$end';\n";
$s=doquery($query);

doquery("begin");

while(($id)=$s->fetchrow())
{
    $query ="insert into invoices values(nextval('invoice_no'),\n";
    $query.="    $id, '$start', '$end')\n";
    doquery($query);
}

doquery("end");
