#!/bin/sh
# Copyright (c) 2002  Dustin Sallings <dustin@spy.net>
# $Id: makeifrrd,v 1.1 2002/03/29 09:22:26 dustin Exp $

for i in "$@"
do
	/usr/local/rrdtool-1.0.33/bin/rrdtool create "$i" \
		-s 60 \
		DS:in:COUNTER:300:0:1250000 \
		DS:out:COUNTER:300:0:1250000 \
		RRA:AVERAGE:0.5:5:8640 \
		RRA:MAX:0.5:5:8640 \
		RRA:AVERAGE:0.5:120:2160 \
		RRA:MAX:0.5:120:2160 \
		RRA:AVERAGE:0.5:1440:1825 \
		RRA:MAX:0.5:1440:1825
done
