#!/bin/sh

hookLog() {
	echo "hook:  $@"
}

HO=/tmp/hook.out
touch $HO
echo "$@" >> $HO
env | sort >> $HO
echo "" >> $HO

# For commits
if [ "$1" == "commit" ]
then
	# If this is my default archive, let's do a local push replication.  My
	# mirror will never be out of date.
	if [ "$ARCH_ARCHIVE" = "dustin@spy.net--projects-2004" ]
	then
		lim=`echo $ARCH_REVISION | sed -e 's,--,;,g' | cut -f-2 -d';' | sed 's,;,--,g'`
		hookLog "Replicating $ARCH_ARCHIVE with limit $lim"
		tla archive-mirror -s $ARCH_ARCHIVE $lim
	else
		hookLog "Not doing anything with $ARCH_ARCHIVE"
	fi
fi
