#!/bin/sh
#
# arch-tag: 707CFF1C-4162-11D8-A45E-000393CFE6B8

hookLog() {
	echo "hook:  $@"
}

# Debug stuff.
if [ "$ARCH_HOOK_DEBUG" == "1" ]
then
	HO=/tmp/hook.out
	touch $HO
	echo "$@" >> $HO
	env | sort >> $HO
	echo "" >> $HO
fi

# For commits
if [ "$1" == "commit" ]
then
	# If this is my default archive, let's do a local push replication.  My
	# mirror will never be out of date.
	if [ "$ARCH_ARCHIVE" = "dustin@spy.net--projects-2004" ]
	then
		lim=`tla parse-package-name $ARCH_REVISION`
		hookLog "Replicating $ARCH_ARCHIVE with limit $lim"
		tla archive-mirror -s $ARCH_ARCHIVE $lim
	else
		hookLog "Not doing anything with $ARCH_ARCHIVE"
	fi
fi
