#!/bin/sh
#
# arch-tag: 707CFF1C-4162-11D8-A45E-000393CFE6B8

hookLog() {
	echo "hook:  $@"
}

# Debug stuff.
if [ "$ARCH_HOOK_DEBUG" == "1" ]
then
	HO=/tmp/hook.out
	touch $HO
	echo "$@" >> $HO
	env | sort >> $HO
	echo "" >> $HO
fi

# For commits
if [ "$1" == "commit" ]
then
	# If there's a mirror for this archive, update it.
	if [ -f "${HOME}/.arch-params/=locations/${ARCH_ARCHIVE}-MIRROR" ]
	then
		lim=`tla parse-package-name $ARCH_REVISION`
		hookLog "Replicating $ARCH_ARCHIVE with limit $lim"
		tla archive-mirror -s $ARCH_ARCHIVE $lim
	else
		hookLog "Not doing anything with $ARCH_ARCHIVE"
	fi
fi
