#!/bin/sh

# Publish from the default archive

if [ $# -lt 2 ]
then
	echo "Usage:  $0 revision destdir"
	exit 1
fi

archive=`tla my-default-archive`
loc=`tla whereis-archive $archive`
rev=$1
dir=$2

echo "Archive-Name: $archive"
echo "Archive-Location: $loc"
echo "Target-Revision: $rev"
echo "Target-Directory: $dir"
