#!/bin/sh
# arch-tag: 91F90E48-441D-11D8-9167-000A957659CC
#
# Automatically find anything that can be mirrored, and mirror it.

t=tla

todo=`$t archives | egrep -- -SOURCE | sed s/-SOURCE//g`
for a in $todo
do
	# Allow for optional limits per-archive.
	if [ -f ${HOME}/.arch-params/=mirror-limits/$a ]
	then
		for lim in `cat ${HOME}/.arch-params/=mirror-limits/$a`
		do
			$t archive-mirror -s $a $lim
		done
	else
		$t archive-mirror -s $a
	fi
done
