#!/bin/sh
# Copyright (c) 1997  SPY Internetworking
# $Id: routersinfo,v 1.1 1997/12/14 21:33:07 dustin Exp $


set kludge { $*
    shift
    shift
    if test -f ../scotty ; then
      exec ../scotty -nf $0 $*
    else
      exec /usr/local/bin/scotty -nf $0 $*
    fi
}

mib load rfc1213.mib
mib load rfc1696.mib
mib load cisco.mib

set file [lindex $argv 0]

if [catch {open $file} input] {
    exit 1
}

set infos { "ifDescr" "locIfDescr" "locIfHardType" "locIfLineProt"
        "locIfLastIn" "locIfLastOut" "locIfInBitsSec" "locIfOutBitsSec"
        "locIfCollisions"
        "locIfInCRC" "locIfInFrame" "locIfInIgnored" "locIfInAbort"
        "locIfResets" "locIfReason" }

while {[gets $input line] != -1} {
    set host "[lindex $line 0]"
    set community [expr {[llength $line] == 2 ? [lindex $line 1] : "public"}]

    set pt [lindex [lindex [icmp echo $host] 0] 1]

    if { $pt>-1 } {

        set code [catch {snmp session -address $host -community $community} s]

        set what "ifNumber.0"
        set code [catch {set nint [lindex [lindex [$s get $what] 0] 2]}]
        if $code {
            set nint 0
        }

        puts -nonewline "$host;$nint"

            for {set i 1} {$i <= $nint} {incr i} {
                foreach what $infos {
                set thing "$what.$i"
                    set code [catch {set ans [lindex [lindex [$s get $thing] 0] 2]}]
                    if $code {
                        set ans "N/A"
                    }
                    puts -nonewline ";$ans"
                }
            }
                puts ""
        }
}

exit 0
