#!/usr/local/bin/perl
# Copyright (c) 1997  Dustin Sallings
# $Id: scoreinsert,v 1.1 1998/01/12 09:12:23 dustin Exp $
#
# This is used to insert messages into the database and
# puts them in the webroot for viewing.

use Postgres;
use MD5;

$messdir="/usr/people/httpd/bulk/messages";

sub ensurePath
{
    local($fn)=@_;
    local(@a, $np);

    if(-d $fn)
    {
        return();
    }

    @a=split(/\//, $fn);

    pop(@a);
    $np=join('/', @a);
    &ensurePath($np);

    if(! -d $np )
    {
        mkdir($np, 0755);
    }
}

sub getFilename
{
    my($spammer)=@_;
    my($name, $time, $i);

    $time=time();

    for($i=0; $i<999999; $i++)
    {
	$name="$spammer/$time.$i";

	last unless(-f "$messdir/$name");
    }
    return($name);
}

sub checkId
{
    my($id)=@_;
    my($query, $count, $s);

    if($id eq "")
    {
	return(-1);
    }

    $query="select count(*) from bill_info where spam_id=$id;";

    if(!($s=$dbh->execute($query)))
    {
	print "ERROR:\n$query\n$Postgres::error\n";
	return(-1);
    }

    ($count)=$s->fetchrow();

    if($count>0)
    {
	return(0);
    }

    return(-1);
}

sub checkAgnt
{
    my($id)=@_;
    my($query, $count, $s);

    if($id eq "")
    {
	return(-1);
    }

    $query="select count(*) from agents where agent_id=$id;";

    if(!($s=$dbh->execute($query)))
    {
	print "ERROR:\n$query\n$Postgres::error\n";
	return(-1);
    }

    ($count)=$s->fetchrow();

    if($count>0)
    {
	return(0);
    }

    return(-1);
}

$dbh=db_connect("spam");

umask 022;

sub scoremsg
{
    my($infile)=@_;
    my($dbh, $query, $s, @r, @scores, %score, %custs);

    $dbh=db_connect("spam");

    if(!$dbh)
    {
        print "Couldn't connect to database\n$Postgres::error\n";
        exit(1);
    }

    $query="select domain, spam_id, score from custmap\n";

    if(!($s=$dbh->execute($query)))
    {
        print "Error in query:\n$query\n$Postgres::error\n";
        exit(1);
    }

    while(@r=$s->fetchrow())
    {
        $custs{$r[0]}=$r[1];
        $score{$r[0]}=$r[2];
    }

    open(IN, $infile) || die("Can't open $infile: $!\n");
    while(<IN>)
    {
        foreach $key (keys(%custs))
        {
            $scores[$custs{$key}]+=$score{$key} if(/$key/i);
        }
    }
    close(IN);

    $i=-1;
    for(0..$#scores)
    {
       $i=$_ if($scores[$_]>$i);
    }

    return($i, $scores[$i]);
}

($file, $agent)=@ARGV;

($spammer, $score)=&scoremsg($file);

if($spammer<0)
{
    print "Damn, looks like you looking that one up...\n";
    exit(0);
}

if(checkId($spammer))
{
    print "Invalid SPAM Id:  $spammer\n";
    exit(1);
}

if(checkAgnt($agent))
{
    print "Invalid AGENT:  $agent\nUsing default agent, 0\n";
    $agent=0;
}

print "Looks like it belongs to $spammer, score was $score\n";

$size=(stat($file))[7];

print "Size:\t$size\n";

open(F, $file);

while(<F>)
{
    chop;
    last if(/^$/);

    if(/Subject: (.*)/)
    {
        $subject=$1;
    }

    if(/^Date:[^0-9]*([0-9]+) ([A-z]{3}) ([0-9]{4}) ([:0-9]{8}) ([-+0-9]+)/)
    {
	$date="$2 $1 $3 $4 $5";
    }

    if(/^Date:[^0-9]*([0-9]+) ([A-z]{3}) ([0-9]{2}) ([:0-9]{8}) ([-+0-9]+)/)
    {
	$date="$2 $1 19$3 $4 $5";
    }

    if(/^Date:[^0-9]*([0-9]+) ([A-z]{3}) ([0-9]{2}) ([:0-9]{8}) ([A-Z]+)/)
    {
	$date="$2 $1 19$3 $4 $5";
    }

    if(/^Date:[^0-9]*([0-9]+) ([A-z]{3}) ([0-9]{4}) ([:0-9]{8}) ([A-Z]+)/)
    {
	$date="$2 $1 $3 $4 $5";
    }
}

print "Subject:\t$subject\n";
print "Date:\t$date\n";

$md5=new MD5;
$md5->reset;
while(<F>)
{
    $md5->add($_);
}

$digest=$md5->hexdigest;

print "Checksum:\t$digest\n";


$fn=&getFilename($spammer);

$subject=~s/\'/\\\'/g;

$dbh->execute("begin");

$query ="insert into messages values($spammer,\n";
$query.="    $agent,\n";
$query.="    '$fn',\n";
$query.="    '$subject',\n";
$query.="    '$digest',\n";
$query.="    $size,\n";
$query.="    '$date');\n";

if(!($dbh->execute($query)))
{
    print "ERROR:\n$query\n$Postgres::error\n";
    $dbh->execute("abort");
    exit(0);
}

$amount=sprintf("%.2f", ($size/1024)*5);

$query ="insert into trans values($spammer,\n";
$query.="    $amount,\n";
$query.="    '$size byte message',\n";
$query.="    '$fn');\n";

if(!($dbh->execute($query)))
{
    print "ERROR:\n$query\n$Postgres::error\n";
    $dbh->execute("abort");
    exit(0);
}

$dbh->execute("commit");

&ensurePath("$messdir/$fn");
system("cp $file $messdir/$fn");
chmod (0644, "$messdir/$fn");
