/*
 * Copyright (c) 2002  Dustin Sallings <dustin@spy.net>
 *
 * $Id: buildit.c,v 1.2 2002/02/06 01:47:19 dustin Exp $
 */
#include <stdio.h>
#include <assert.h>

#include "scrabble.h"

static void
buildScores()
{
	FILE *f;
	int i;

	f=fopen("scores.c", "w");
	assert(f);

	printf("Building scores.c\n");

	fprintf(f, "/* This file is automatically generated. */\n\n");
	fprintf(f, "int scores[]={\n\t");

	for(i=0; i<256; i++) {
		fprintf(f, "%d, ", originalScoreLetter((char)i));
		if(i>0 && (i%16)==0) {
			fprintf(f, "\n\t");
		}
	}

	fprintf(f, "};\n\n");

	fclose(f);
}

static void
buildDictionary()
{
	FILE *f;
	struct dict_entry **dict=NULL;
	int i;

	printf("Building dictionary.c and dictionary.h\n");

	dict=loadDict();
	assert(dict);

	/* First make dictionary.c */

	f=fopen("dictionary.h", "w");
	assert(f);

	fprintf(f, "/* This file is automatically generated. */\n\n");
	fprintf(f, "#ifndef DICTIONARY_H\n#define DICTIONARY_H 1\n\n");

	for(i=0; dict[i]; i++);

	fprintf(f, "#define DICTIONARY_SIZE %d\n\n", i);

	fprintf(f, "#endif /* DICTIONARY_H */\n\n");

	fclose(f);

	/* Now make dictionary.c */

	f=fopen("dictionary.c", "w");
	assert(f);

	fprintf(f, "/* This file is automatically generated. */\n\n");
	fprintf(f, "#include \"scrabble.h\"\n\n");
	fprintf(f, "struct dict_entry dictionary[DICTIONARY_SIZE]={\n");

	for(i=0; dict[i]!=NULL; i++) {
		fprintf(f, "\t{\"%s\", %d},\n", dict[i]->word, dict[i]->score);
	}

	fprintf(f, "};\n\n");
	fclose(f);
}

int
main(int argc, char **argv)
{
	buildScores();
	buildDictionary();
	return(0);
}
