#!/bin/sh
#
# arch-tag: DB517CB1-9CD6-11D8-8C7E-000393CFE6B8

for i in "$@"
do
	echo "Doing first grep on $i"
	gzip -dc < $i/results.log.gz \
		| egrep "Out of session structures|connection after IO error" \
		| gzip -3vc > $i/grep.one.gz

	echo "Doing split grep on $i"
	gzip -dc $i/grep.one.gz | egrep "Out of session structures" \
		| gzip -3vc > $i/grep.session.gz
	gzip -dc $i/grep.one.gz | egrep "connection after IO error" \
		| gzip -3vc > $i/grep.ioerr.gz

	echo "Finding unique serial numbers"
	gzip -dc $i/grep.session.gz | awk '{print $1}' | sort -u > $i/session.sn
	gzip -dc $i/grep.ioerr.gz | awk '{print $1}' | sort -u > $i/ioerr.sn

done
