#!/bin/sh

FILE=$1
dir=`dirname $FILE`

echo "Doing first grep on $FILE (dir is $dir)"
gzip -dc < $FILE \
	| egrep "Out of session structures|connection after IO error" \
	| gzip -3vc > $dir/,grep.one.gz

echo "Doing split grep on $FILE"
gzip -dc $dir/,grep.one.gz | egrep "Out of session structures" \
	| gzip -3vc > $dir/grep.session.gz
gzip -dc $dir/,grep.one.gz | egrep "connection after IO error" \
	| gzip -3vc > $dir/grep.ioerr.gz

echo "Finding unique serial numbers"
gzip -dc $dir/grep.session.gz | awk '{print $1 " " $2}' \
	| sort -u > $dir/session.sn
gzip -dc $dir/grep.ioerr.gz | awk '{print $1 " " $2}' \
	| sort -u > $dir/ioerr.sn
