    <tr>
        <td><a href="%CGIDIR%/admin/admin.cgi?func=display&oid=%OID%">
	<img border="0" src="%CGIDIR%/img.cgi/tn/%IMAGE%"></a></tr>
        <td><a href="%CGIDIR%/admin/admin.cgi?func=deleteImage&oid=%OID%">
             %OID%</a></td>
        <td>%CAT%</td>
        <td><a href="%CGIDIR%/admin/admin.cgi?func=display&oid=%OID%">
             %KEYWORDS%</a></td>
        <td>%TAKEN%</td>
        <td>%TS%</td>
    </tr>
