    <tr>
        <td><a href="%CGIDIR%/admin/admin.cgi?func=display&id=%IMAGE%">
	<img border="0" src="%CGIDIR%/img.cgi/tn/%IMAGE%"></a></tr>
        <td><a href="%CGIDIR%/admin/admin.cgi?func=deleteImage&id=%IMAGE%">
             %IMAGE%</a></td>
        <td>%CAT%</td>
        <td><a href="%CGIDIR%/admin/admin.cgi?func=display&id=%IMAGE%">
             %KEYWORDS%</a></td>
        <td>%TAKEN%</td>
        <td>%TS%</td>
    </tr>
