#!/usr/local/bin/perl
# Copyright (c) 1998  Dustin Sallings
#
# $Id: playmp3,v 1.2 1998/03/26 07:51:05 dustin Exp $

use LWP::UserAgent;
use Tk;

$index="http://dominance.west.spy.net/mp3/index.txt";
$base="http://dominance.west.spy.net/mp3";

sub getfile
{
    my($ua,$req,$res);
    $ua=LWP::UserAgent->new;
    $ua->agent('DustinPlayer/0.1' . $ua->agent);
    $req=HTTP::Request->new('GET', $_[0]);
    $res=$ua->request($req);
    return($res->content);
}

sub playtrack
{
    my($a, $b, $c)=@_;
    system('/usr/local/bin/mpg123', "$base/$a/$b/$c") unless(fork());
}

sub listpopup
{
    my($title, $label, $sub, @list)=@_;

    my($top, $nm);
    $MW=MainWindow->new;
    $MW->title($title);
    $MW->Label(-text => $label)->pack;
    $nm=$MW->Scrolled(Listbox, -scrollbars => 'e')
             ->pack(-expand => 'yes', -fill => 'x');
    $nm->insert(0, sort(@list));
    $nm->bind('<Double-1>' => $sub);

}

sub showalbum
{
    my($k, $a)=@_;
    listpopup('Track Select', 'Select the track you wish to play.',
	      sub { playtrack($k,$a,$_[0]->get('active')); },
	      @{$h{$k}{$a}});
}

sub showband
{
    my($k)=@_;
    listpopup('Album Select', 'Select from one of the following albums.',
	      sub { showalbum($k, $_[0]->get('active')); },
	      keys(%{$h{$k}}) );
}

# Processing index.
map {
    @a=split(/\//);
    push(@{$h{$a[0]}{$a[1]}}, $a[2]);
} split(/\n/, getfile($index));

listpopup('Band Select', 'Select from one of the following bands.',
	  sub { showband($_[0]->get('active')); },
	  keys(%h));

MainLoop;
