#!/bin/sh
# Copyright (c) 2000  Dustin Sallings <dustin@spy.net>
# $Id: checkntp,v 1.2 2000/09/12 03:24:42 dustin Exp $ \
exec scotty "$0" "$@"

proc checkNTPInfo { host } {
	set e ""
	set ok 0

	ntp $host vars
	# Debug info
	puts "Here's what we got:"
	foreach k [ array names vars ] {
		puts "\t$k: $vars($k)"
	}

	catch {

		if { ! [info exists vars(peer.dispersion)] } {
			set vars(peer.dispersion) 0.0
		} else {
			# puts "$host dispersion is $vars(peer.dispersion)"
		}

		if { ! [info exists vars(peer.offset)] } {
			# error "Did not get offset information from $host"
			# If we don't have it, could it be that it's zero?
			set vars(peer.offset) $vars(peer.dispersion)
		}

		if { $vars(peer.offset) > 50 } {
			error "Peer NTP offset is $vars(peer.offset)"
		}

		set ok 1
	} e

	if { $ok == 0 } {
		# puts "Got an error:  $e"
		error $e
	}
}

set exit_code 0

foreach host $argv {
	if { [catch { checkNTPInfo $host } e ] } {
		puts "Problem with $host:  $e"
		set exit_code 2
	} else {
		puts "$host is OK"
	}
}

exit $exit_code
