#!/bin/sh
#
# $Id: gather,v 1.3 2000/01/12 00:58:15 dustin Exp $

# URL=http://coyote.beyond.com:7001/larryktest
# URL=http://coyote.beyond.com:7001/xmltest
# WEBSPLAT_POST=xml.post
# WEBSPLAT=../websplat

# Configuration parameters.
SETSIZE=100
MAX_CONCURRENCY=50

gatherdata() {
	echo "*** $1 simultaneous ***"
	# $WEBSPLAT -f -S -n $1 -t $SETSIZE $URL | tee data/set$2.dat
	./cmd -f -S -n $1 -t $SETSIZE | tee data/set$2.dat
}

# Make sure the data directory exists.
if [ ! -d data ]
then
	mkdir data
fi

N=0
for i in ` perl -e "$,=\" \"; print (1..${MAX_CONCURRENCY})" `
do
	N=`expr $N + 1`
	gatherdata $i $N
done
