#!/usr/bin/env python

import sys
import posix
import re

smso=posix.popen("tput smso").read()
rmso=posix.popen("tput rmso").read()

expression=re.compile("(" + sys.argv[1] + ")")
l=sys.stdin.readline()

while l != '':
	s=expression.sub(smso + '\\1' + rmso, l)
	sys.stdout.write(s)
	l=sys.stdin.readline()
