#!/usr/bin/env python
# mv that can move the contents of a directory into its subdirectory.
# Kind of lame, but I needed it for a git tree filter.

import os
import sys

if __name__ == '__main__':
	dest = sys.argv[1]

	if not os.path.exists(dest):
		os.makedirs(dest)

	stuff = os.listdir(".")
	print "Found", stuff
	for p in stuff:
		if p != dest:
			d = os.path.join(dest, p)
			print p, "->", d
			os.rename(p, d)
