<table>
<tr>

    <td>
        Keywords: %KEYWORDS%<br>
        Category:  %CAT%<br>
        Size:  %SIZE% bytes<br>
        Taken:  %TAKEN%<br>
        Added:  %TS% by %ADDEDBY%<br>
    </td>

    <td>
	<a href="%SELF_URI%?func=display&search_id=%ID%">
        <img border="0"
		src="%SELF_URI%?func=getimage&photo_id=%IMAGE%&thumbnail=1"></a>
    </td>

</tr>
</table>

<blockquote>
%DESCR%
</blockquote>
