<table>
<tr>

    <td>
	    <font face="Ariel,Helvetica">
        Keywords: %KEYWORDS%<br>
        Category:  %CAT%<br>
        Size:  %SIZE% bytes<br>
        Taken:  %TAKEN%<br>
        Added:  %TS% by %ADDEDBY%<br>
		</font>
    </td>

    <td>
	<a href="%SELF_URI%?func=display&oid=%OID%">
        <img border="0" src="%CGIDIR%/img.cgi/tn/%IMAGE%"></a>
    </td>

</tr>
</table>

<blockquote>
%DESCR%
</blockquote>
