<hr align="left" width="50%"> <!-- % -->
<font size="-2">
Copyright &copy; 1997-2000 Dustin Sallings of <a href="http://www.spy.net/">
SPY Internetworking</a>
<br>
All Images and other data within these pages are property of their owners,
and may not be used without permission.
<br>
<a href="%SELF_URI%?func=credform">Authenticated as:
%REMOTE_USER% (%REMOTE_UID%)</a><br>
Last modified %LAST_MODIFIED%<br>
</font>
