#!/bin/sh
# Beyond.com test order

HOST=monty.spice:8101

./websplat $* "\
http://${HOST}/orders/order.htm?email=brutaltester%40foo%2Enet&em\
ail2=brutaltester%40foo%2Enet&ship_first_name=Brutal&ship_last_name=Tester&c\
ompany=%20&ship_address_1=HardKnocks%20St%2E&ship_address_2=%20&ship_city=Ne\
w%20York&ship_state_province=NY&ship_postal_code=10223&ship_country_code=US&\
ship_phone=2124332345&bill_first_name=Brutal&bill_last_name=Tester&bill_addr\
ess_1=HardKnocks%20St&bill_address_2=%20&bill_city=New%20York&bill_state_pro\
vince=NY&bill_postal_code=10223&bill_country_code=US&bill_phone=2124332345&m\
ailings=Y&shipsame=us&usbillinfo=Continue&ReferrerName=NITRO&ShopperKey=Shop\
_key_984592922&LocalTransID=85&TransactionKey=Trans_Key984592922"
