#!/bin/sh
#
# $Id: gather,v 1.1 1999/09/01 21:07:01 dustin Exp $

URL=http://coyote.beyond.com:7001/larryktest
WEBSPLAT_POST=xml.post
WEBSPLAT=../websplat

gatherdata() {
	echo "*** $1 simultaneous ***"
	$WEBSPLAT -f -S -n $1 -t 128 $URL | tee data/set$2.dat
}

N=0
for i in ` perl -e '$,=" "; print (1..256)' `
do
	N=`expr $N + 1`
	gatherdata $i $N
done
