#!/usr/local/bin/perl -w
# This was written by Dustin Sallings for David Rarick for use with
# MobileComm's WWW Paging Client thing.
# Made to work under IRIX 6.2, should work anywhere, probably doesn't.
# $Id: webpage,v 1.4 1997/11/24 07:04:14 dustin Exp $

use strict;

# Username -> pin mapping
my %Users=(
    'drarick' => 8203941,
);

# In case of an alarm (connection timeout), just reset the alarm handler
# and return.

sub alarmhandler
{
    alarm(0);
    $SIG{'ALRM'}='alarmhandler';
    return(0);
}

# Encode a character into a %XX value.

sub myurlencode
{
    my($char)=@_;
    my($return);

    $return=unpack("c", $char);
    $return=sprintf("%%%X", $return);
    return($return);
}

sub SendPage
{
    my($pin, $message)=@_;
    my($host, $formdata);
    my($name, $aliases, $type, $len, $thisaddr, $thataddr, $port, $proto);
    my($me, $rem);
    my $sockaddr='S n a4 x8';
    my $remote="www.mobilecomm.com";

    ($name, $aliases, $proto)=getprotobyname('tcp');
    ($name, $aliases, $port)=getservbyname(80, 'tcp');

    ($name, $aliases, $type, $len, $thisaddr)=gethostbyname('0.0.0.0');
    ($name, $aliases, $type, $len, $thataddr)=gethostbyname($remote);
    if($name eq "")
    {
	print "Unable to resolve hostname: $host\n";
	return;
    }
    $me=pack($sockaddr, 2, 0, $thisaddr);
    $rem=pack($sockaddr, 2, 80, $thataddr);

    if(!socket(S, 2, 2, $proto))
    {
	print "Can't open socket: $!\n";
	return;
    }

    if(!bind(S, $me))
    {
	print "Can't bind socket: $!\n";
	return;
    }

    # Thirty seconds should be plenty long enough to connect.
    $SIG{'ALRM'}='alarmhandler';
    alarm(30);

    if(!connect(S, $rem))
    {
	print "Can't connect to $remote: $!\n";
	return;
    }

    alarm(0);

    select(S); $|=1; select(STDOUT); $|=1;

    $message=~s/([^A-z0-9])/&myurlencode($1)/ge;
    $formdata="PIN=$pin&MSSG=$message";

    print S "POST /scripts/mobilecomm/wwwpage.exe HTTP/1.0\n";
    print S "Content-length: " . length($formdata) . "\n";
    print S "Content-type: application/x-www-form-urlencoded\n\n";
    print S $formdata;

    # This eats the web page they send us.
    while(<S>) {}
}

#################################################
#
# This is the beginning.
#
#################################################

# Grab the arguments.  First arg is a pin, everything after that is
# combined with a space to make the message.

my $pin=shift;
if(defined($Users{$pin}))
{
    print "Looking up $pin\n";
    $pin=$Users{$pin};
}

my $message=join(' ', @ARGV);

# Call the page sender.

SendPage($pin, $message);
