#!/usr/local/bin/perl
# Modify all people

use Net::LDAP;

$|=1;
print "Enter password:  ";
$|=0;
my $pass=<>;
chomp($pass);

my $ldap=Net::LDAP->new("dhcp-104");
my $res=$ldap->bind('uid=dustin,ou=agents,dc=spy,dc=net', 'password' => $pass);
if($res->code()!=0) {
	print "Error authenticating:  " . $res->code() . "\n";
	exit(-1);
}

my(@dns)=();

$result = $ldap->search ( 'base' => 'ou=agents,dc=spy,dc=net',
	'scope' => 'sub', 'filter' => "(objectclass=*)", 'attrs' => [ 'uid' ]);

for $entry ($result->all_entries()) {
	push(@dns, $entry->dn());
}

for(@dns) {
	print "Modifying $_...";
	my $r=$ldap->modify($_, "delete" => {'objectClass', 'account'});
	if($r->code()==0) {
		print "ok\n";
	} else {
		print "failed (" . $r->code() . ")\n";
	}
}
