#!/usr/local/bin/perl
# $Id: scanlogs,v 1.1 1997/12/14 21:32:54 dustin Exp $

push(@INC, "/home/monitor/lib");
require "statlib.pl";

%ht=readInLogstuff();

# foreach $key (keys(%ht))
# {
#     print "$key:\n\t$ht{$key}[0]\n\t$ht{$key}[1]\n";
# }

@files=("/var/log/pixlog", "/var/adm/messages");

for $file (@files)
{
    %res=scanLogFile($file);

    for $key (sort(keys(%res)))
    {
        print "$ht{$key}[1]:  $res{$key}\n";
    }
}
